export const sampleListings = [
  {
    id: "idealista-pt-1001",
    source: "Idealista",
    title: "T2 renovado com varanda",
    zone: "Alvalade",
    city: "Lisboa",
    rooms: 2,
    price: 285000,
    listingType: "buy",
    url: "https://www.idealista.pt/comprar-casas/lisboa/alvalade/",
  },
  {
    id: "idealista-pt-1002",
    source: "Idealista",
    title: "T1 para arrendar no centro",
    zone: "Arroios",
    city: "Lisboa",
    rooms: 1,
    price: 1450,
    listingType: "rent",
    url: "https://www.idealista.pt/arrendar-casas/lisboa/arroios/",
  },
  {
    id: "idealista-pt-1003",
    source: "Idealista",
    title: "T3 familiar com garagem",
    zone: "Bonfim",
    city: "Porto",
    rooms: 3,
    price: 275000,
    listingType: "buy",
    url: "https://www.idealista.pt/comprar-casas/porto/bonfim/",
  },
  {
    id: "idealista-pt-1004",
    source: "Idealista",
    title: "T2 junto ao metro",
    zone: "Paranhos",
    city: "Porto",
    rooms: 2,
    price: 1200,
    listingType: "rent",
    url: "https://www.idealista.pt/arrendar-casas/porto/paranhos/",
  },
  {
    id: "idealista-pt-1005",
    source: "Idealista",
    title: "T3 com luz natural",
    zone: "Sao Vicente",
    city: "Braga",
    rooms: 3,
    price: 198000,
    listingType: "buy",
    url: "https://www.idealista.pt/comprar-casas/braga/sao-vicente/",
  },
  {
    id: "idealista-pt-1006",
    source: "Idealista",
    title: "Moradia T4 com jardim",
    zone: "Azeitao",
    city: "Setubal",
    rooms: 4,
    price: 330000,
    listingType: "buy",
    url: "https://www.idealista.pt/comprar-casas/setubal/azeitao/",
  },
  {
    id: "idealista-pt-1007",
    source: "Idealista",
    title: "T1 no centro historico",
    zone: "Santo Ildefonso",
    city: "Porto",
    rooms: 1,
    price: 950,
    listingType: "rent",
    url: "https://www.idealista.pt/arrendar-casas/porto/santo-ildefonso/",
  },
  {
    id: "imovirtual-pt-2001",
    source: "Imovirtual",
    title: "T2 moderno perto do parque",
    zone: "Avenidas Novas",
    city: "Lisboa",
    rooms: 2,
    price: 420000,
    listingType: "buy",
    url: "https://www.imovirtual.com/pt/resultados/comprar/apartamento/lisboa/lisboa",
  },
  {
    id: "imovirtual-pt-2002",
    source: "Imovirtual",
    title: "T2 para arrendamento",
    zone: "Benfica",
    city: "Lisboa",
    rooms: 2,
    price: 1300,
    listingType: "rent",
    url: "https://www.imovirtual.com/pt/resultados/arrendar/apartamento/lisboa/lisboa",
  },
  {
    id: "imovirtual-pt-2003",
    source: "Imovirtual",
    title: "T3 com varanda ampla",
    zone: "Matosinhos Sul",
    city: "Porto",
    rooms: 3,
    price: 310000,
    listingType: "buy",
    url: "https://www.imovirtual.com/pt/resultados/comprar/apartamento/porto/porto",
  },
  {
    id: "imovirtual-pt-2004",
    source: "Imovirtual",
    title: "T1 remodelado",
    zone: "Campanha",
    city: "Porto",
    rooms: 1,
    price: 1100,
    listingType: "rent",
    url: "https://www.imovirtual.com/pt/resultados/arrendar/apartamento/porto/porto",
  },
  {
    id: "imovirtual-pt-2005",
    source: "Imovirtual",
    title: "T3 com arrecadacao",
    zone: "Montenegro",
    city: "Faro",
    rooms: 3,
    price: 295000,
    listingType: "buy",
    url: "https://www.imovirtual.com/pt/resultados/comprar/apartamento/faro/faro",
  },
  {
    id: "imovirtual-pt-2006",
    source: "Imovirtual",
    title: "T1 no centro universitario",
    zone: "Solum",
    city: "Coimbra",
    rooms: 1,
    price: 950,
    listingType: "rent",
    url: "https://www.imovirtual.com/pt/resultados/arrendar/apartamento/coimbra/coimbra",
  },
  {
    id: "casa-sapo-3001",
    source: "Casa Sapo",
    title: "T3 com terraco",
    zone: "Lumiar",
    city: "Lisboa",
    rooms: 3,
    price: 350000,
    listingType: "buy",
    url: "https://casa.sapo.pt/comprar-casas/lisboa/lisboa/lumiar/",
  },
  {
    id: "casa-sapo-3002",
    source: "Casa Sapo",
    title: "T2 mobilado para arrendamento",
    zone: "Parque das Nacoes",
    city: "Lisboa",
    rooms: 2,
    price: 1800,
    listingType: "rent",
    url: "https://casa.sapo.pt/arrendar-apartamentos/lisboa/lisboa/parque-das-nacoes/",
  },
  {
    id: "casa-sapo-3003",
    source: "Casa Sapo",
    title: "T4 com vista para o mar",
    zone: "Foz do Douro",
    city: "Porto",
    rooms: 4,
    price: 540000,
    listingType: "buy",
    url: "https://casa.sapo.pt/comprar-casas/porto/porto/foz-do-douro/",
  },
  {
    id: "casa-sapo-3004",
    source: "Casa Sapo",
    title: "T1 moderno para arrendamento",
    zone: "Cedofeita",
    city: "Porto",
    rooms: 1,
    price: 1250,
    listingType: "rent",
    url: "https://casa.sapo.pt/arrendar-apartamentos/porto/porto/cedofeita/",
  },
  {
    id: "casa-sapo-3005",
    source: "Casa Sapo",
    title: "T3 para familia",
    zone: "Nogueiro",
    city: "Braga",
    rooms: 3,
    price: 275000,
    listingType: "buy",
    url: "https://casa.sapo.pt/comprar-casas/braga/braga/nogueiro/",
  },
  {
    id: "casa-sapo-3006",
    source: "Casa Sapo",
    title: "T1 com varanda",
    zone: "Gloria",
    city: "Aveiro",
    rooms: 1,
    price: 900,
    listingType: "rent",
    url: "https://casa.sapo.pt/arrendar-apartamentos/aveiro/aveiro/gloria/",
  },
  {
    id: "remax-pt-4001",
    source: "REMAX",
    title: "T3 com varanda e garagem",
    zone: "Carcavelos",
    city: "Cascais",
    rooms: 3,
    price: 465000,
    listingType: "buy",
    url: "",
  },
  {
    id: "remax-pt-4002",
    source: "REMAX",
    title: "T2 mobilado junto ao metro",
    zone: "Odivelas",
    city: "Lisboa",
    rooms: 2,
    price: 1350,
    listingType: "rent",
    url: "",
  },
  {
    id: "era-pt-5001",
    source: "ERA",
    title: "T2 remodelado com varanda",
    zone: "Amadora",
    city: "Lisboa",
    rooms: 2,
    price: 245000,
    listingType: "buy",
    url: "",
  },
  {
    id: "era-pt-5002",
    source: "ERA",
    title: "T1 perto do parque",
    zone: "Vila Nova de Gaia",
    city: "Porto",
    rooms: 1,
    price: 980,
    listingType: "rent",
    url: "",
  },
  {
    id: "century21-pt-6001",
    source: "Century 21",
    title: "T3 com vista desafogada",
    zone: "Lumiar",
    city: "Lisboa",
    rooms: 3,
    price: 410000,
    listingType: "buy",
    url: "",
  },
  {
    id: "century21-pt-6002",
    source: "Century 21",
    title: "T1 no centro historico",
    zone: "Cedofeita",
    city: "Porto",
    rooms: 1,
    price: 1100,
    listingType: "rent",
    url: "",
  },
  {
    id: "zome-pt-7001",
    source: "Zome",
    title: "Moradia T4 com jardim",
    zone: "Azeitao",
    city: "Setubal",
    rooms: 4,
    price: 520000,
    listingType: "buy",
    url: "",
  },
  {
    id: "zome-pt-7002",
    source: "Zome",
    title: "T2 com suite e varanda",
    zone: "Paranhos",
    city: "Porto",
    rooms: 2,
    price: 1600,
    listingType: "rent",
    url: "",
  },
  {
    id: "kw-pt-8001",
    source: "KW Portugal",
    title: "T3 com vista rio",
    zone: "Almada",
    city: "Setubal",
    rooms: 3,
    price: 375000,
    listingType: "buy",
    url: "",
  },
  {
    id: "kw-pt-8002",
    source: "KW Portugal",
    title: "T2 com arrecadacao",
    zone: "Viseu",
    city: "Viseu",
    rooms: 2,
    price: 950,
    listingType: "rent",
    url: "",
  },
];
